# Generated by Django 4.0 on 2021-12-18 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_user_department_alter_department_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(to='company.Department', verbose_name='Департаменты'),
        ),
        migrations.AlterField(
            model_name='department',
            name='client',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
